[variables]
PKG_CONFIG_PATH = "/usr/lib/pkgconfig:/usr/share/pkgconfig:/root/.nix-profile/lib/pkgconfig"
C_INCLUDE_PATH = "/root/.nix-profile/include"
LIBRARY_PATH = "/root/.nix-profile/lib"
LD_LIBRARY_PATH = "/root/.nix-profile/lib"

[phases.setup]
nixPkgs = ["python312", "gcc", "pkg-config", "cairo", "pango", "zlib", "postgresql", "meson", "ninja"]

[phases.install]
cmds = [
  "python -m venv /app/.venv",
  "/app/.venv/bin/pip install --upgrade pip",
  "/app/.venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = ["/app/.venv/bin/python manage.py collectstatic --noinput"]